import type { Metadata } from "next";
import Image from "next/image";
import React from "react";
import { FlipWordsDemo } from "../components/FlipWords";
import {HeroSection} from "../components/heroSection";

export const metadata: Metadata = {
  title: "nee. - Portfolio Framer Template For Freelancers",
  description: "Generated by create next app",
};

export default function About() {
  return (
    <section className="">
      <HeroSection />
    </section>
  );
}
