import type { Metadata } from "next";
import HomeSectionHeader from "./components/homeSectionHeader";
import AdminWeather from "./components/AdminWeather";
import IntroSection from "./components/introSection";
import { ReviewSection } from "./components/reviewSection";

import ExpSection from "./components/ExpSection";
import { VisionSection } from "./components/VisionSection";
import Footer from "./components/footer";

export const metadata: Metadata = {
  title: "nee. - Portfolio Framer Template For Freelancers",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <main className="bg-primary text-secondaryText scroll-smooth focus:scroll-auto">
      <HomeSectionHeader />
      <IntroSection />
      <section className="w-full flex justify-center items-center">
        <div className="w-full">
          <div></div>
        </div>
      </section>
      <section className="">
       <ReviewSection/>
      </section>
      <section id="vision" className=""> 
        <ExpSection/>
      </section>
      <section className="mt-20 ">
        <VisionSection />
      </section>
    </main>
  );
}
