import type { Metadata } from "next";
import DarkModeToggle from "./components/DarkModeToggle";
import HomeSectionHeader from "./components/homeSectionHeader";
import { TypewriterEffectSmoothDemo } from "./components/typeWriter";
import WorkSection from "./components/workSection";

export const metadata: Metadata = {
  title: "bug fixer programmer freelancer",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <main>
      <HomeSectionHeader />
      <TypewriterEffectSmoothDemo />
      <section className="h-[100vh] flex justify-center items-center">
       <WorkSection/>
      </section>
      <section className="h-[100vh] flex justify-center items-center">Vision to learn</section>
    

      <div className="flex flex-col items-center justify-center min-h-screen py-2">
        <DarkModeToggle />
        {/* Other components or content */}
      </div>
    </main>
  );
}
