import type { Metadata } from "next";
import HomeSectionHeader from "./components/homeSectionHeader";
import AdminWeather from "./components/AdminWeather";
import IntroSection from "./components/introSection";
import { ReviewSection } from "./components/reviewSection";

import ExpSection from "./components/ExpSection";
import { VisionSection } from "./components/VisionSection";
import Footer from "./components/footer";
import StickyRelativeDemo from "./components/StickyRelativeDemo";

export const metadata: Metadata = {
  title: "nee. - Portfolio Framer Template For Freelancers",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <main className="bg-primary text-primary scroll-smooth focus:scroll-auto">
      <section className="">
        <HomeSectionHeader />
      </section>
      <section className=" md:h-screen">
        <IntroSection />
      </section>
      <section className="">
        <StickyRelativeDemo />
      </section>
      <section className="">
        <ReviewSection />
      </section>
      <section id="vision" className="">
        <ExpSection />
      </section>
      <section className=" ">
        <VisionSection />
      </section>
    </main>
  );
}
